eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: Zaid-Siddiqui 

microservice:
  payment-service:
    enpoints:
      uri: http://PAYMENT-SERVICE/payment/paymentdone
  order-service:
    enpoints:
      uri: http://TICKET-SERVICE/order/bookticket

    
